version: '3.5'

services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: ./
      dockerfile: .dockerfiles/frontendDev
    ports: 
      - '3000:3000' 
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules/.cache/
    restart: always
volumes:
  postgres: ~