version: '3.5'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /var/lib/postgresql/data
  backend:
    build:
      context: ./
      dockerfile: .dockerfiles/backendDev
    ports:
      - "${BACKEND_PORT}:3050"
    volumes:
      - ./backend:/opt/app
    restart: always
  frontend:
    build:
      context: ./
      dockerfile: .dockerfiles/frontendDev
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules/.cache/
    restart: always
