version: "3.5"

services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 3060
        #managementApiSecret: ${PRISMA_MAS}
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${DB_USERNAME}
            password: ${DB_PASSWORD}
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "3050:3050"
    environment:
      NODE_ENV: production
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_HOST: ${FRONTEND_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SALT_ROUNDS: ${SALT_ROUNDS}
      ROOT_ADMIN_EMAIL: ${ROOT_ADMIN_EMAIL}
      ROOT_ADMIN_PASS: ${ROOT_ADMIN_PASS}
    env_file: .env
    depends_on:
      - prisma
    restart: always
    command: yarn prisma:force-reset
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
    restart: always
volumes:
  postgres: ~
