version: "3.5"

services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 3060
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "3050:3050"
    environment:
      NODE_ENV: production
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_HOST: ${FRONTEND_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      SALT_ROUNDS: ${SALT_ROUNDS}
      ROOT_ADMIN_EMAIL: ${ROOT_ADMIN_EMAIL}
      ROOT_ADMIN_PASS: ${ROOT_ADMIN_PASS}
    env_file: .env
    depends_on:
      - prisma
    restart: always
    volumes:
      - ./logs:/opt/app/logs
    # reset prisma - uncomment bellow line to do it
    #command: yarn prisma reset --force
    # update prisma schema - uncomment bellow line to do it
    #command: yarn prisma deploy --force
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      PUBLIC_URL: ${PUBLIC_URL}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    restart: always
volumes:
  postgres: ~
