version: '3.5'

services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - '3060:3060'
    environment:
      PRISMA_CONFIG: |
        port: 3060
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    build:
      context: ./
      dockerfile: .dockerfiles/backendDev
    ports:
      - '3050:3050'
    volumes:
      - ./backend:/opt/app
    environment:
      NODE_ENV: development
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SALT_ROUNDS: ${SALT_ROUNDS}
    env_file: .env
    restart: always
  frontend:
    build:
      context: ./
      dockerfile: .dockerfiles/frontendDev
    ports: 
      - '3000:3000' 
    volumes:
      - ./frontend:/opt/app
      - /opt/app/node_modules/.cache/
    restart: always
volumes:
  postgres: ~